name: HideRails
version: 0.3.3-SNAPSHOT
authors: [lulucraft321]
description: Plugin for hide rails - By lulucraft321
main: fr.lulucraft321.hiderails.HideRails
commands:
  hiderails:
    aliases: [hr]
    description: Main command